# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_1; end
module T::Private::Methods::MethodHooks; end
module YARD::Logger; end
